import { Inter } from 'next/font/google';
import './globals.css';
import Header from "@/components/Header";
import LeftBar from "@/components/LeftBar";
import RightBar from "@/components/RightBar";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Audidat Clientes',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className="flex bg-white">
          <LeftBar />
          <main className="flex-1 p-2">
            {children}
          </main>
          <RightBar />
        </div>
      </body>
    </html>
  );
}
